# Sistema de evaluación DBP

Ejemplo: Un grupo de 3 estudiantes con las siguientes calificaciones:

| | **E1** | **E2** | **E3** |
|---|---|---|---|
| **E1** | 18 | 19 | 16 |
| **E2** | 14 | 15 | 16 |
| **E3** | 16 | 18 | 17 |


## Paso 1: Recolectar notas

Supongamos que tenemos un grupo de $n$ estudiantes. Cada estudiante $i$ da una autoevaluación $A_i$ y recibe calificaciones $C_{ij}$ de sus compañeros $j$ (donde $j \neq i$).

In [2]:
import numpy as np

n = 3

notas = np.array([
    [18, 19, 16],
    [18, 19, 16],
    [18, 19, 16],
])

prain


## Paso 2: Calcular la desviación estándar

Para cada estudiante, primero calculamos la calificación promedio que recibe de sus compañeros:

$$
prom(C_i) = \frac{1}{n-1} \sum_{j \neq i} C_{ij} \\
$$

Luego, calculamos la desviación estándar de las calificaciones recibidas por cada estudiante:

$$
\sigma_i = \sqrt{\frac{1}{N-1} \sum_{j \neq i}^{N} (C_{ij} - prom(C_i))^2} \\
$$

In [5]:
# Calcular la calificación promedio recibida por cada estudiante
promedios = np.mean(coevaluaciones, axis=1)
print(promedios)

# Calcular la desviación estándar de las calificaciones recibidas
desviaciones = np.std(coevaluaciones, axis=1, ddof=1)
print(desviaciones)

desviaciones_normalizadas = (autoevaluaciones - promedios) / desviaciones
print(desviaciones_normalizadas)

[17.5 15.  17.5]
[2.12132034 1.41421356 0.70710678]
[ 0.23570226  0.         -0.70710678]


## Paso 3: Establecer el factor multiplicativo
Para determinar el factor multiplicativo $F$, podemos usar la relación entre la autoevaluación $A_i$ y la calificación promedio $prom(C_i)$. Por ejemplo, si $A_i$ está significativamente por encima de $prom(C_i)$, se penaliza, y si está significativamente por debajo, se premia.

Podemos definir $F$ como sigue:

$$
F_i = 1 + k \times \frac{A_i - prom(C_i)}{\sigma_i}
$$

donde $k$ es una constante de ajuste para controlar la magnitud del factor. Queremos que $F_i$ esté entre 0.8 y 1.2, por lo que debemos escalar y limitar este valor. 


In [34]:
# Constante de ajuste
k = 0.1

# Calcular el factor multiplicativo para cada estudiante

factores = 1 + k * desviaciones_normalizadas
print(factores)

# Ajustar los factores para que el promedio sea 1
factores = factores / np.mean(factores)

# Limitar el factor multiplicativo entre 0.8 y 1.2
factores = np.clip(factores, 0.8, 1.2)

print("Autoevaluaciones:", autoevaluaciones)
print("Promedios:", promedios)
print("Desviaciones:", desviaciones)
print("Factores multiplicativos:", factores)


Autoevaluaciones: [20 20 20 20]
Promedios: [16.66666667 13.33333333 15.33333333 19.        ]
Desviaciones: [2.081666   3.05505046 3.05505046 1.        ]
Factores multiplicativos: [1.00203279 1.0522064  0.99566227 0.95009854]
